#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# sos installation
python -m sos_notebook.install
jupyter labextension install jupyterlab-sos --no-build 

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build 
jupyter labextension install beakerx-jupyterlab --no-build 

# Git Jupyter/Lab extension 
jupyter labextension install @jupyterlab/git --no-build 
jupyter serverextension enable --py jupyterlab_git

# Jupyter/Lab extension for iframe/url https://github.com/timkpaine/jupyterlab_iframe
jupyter labextension install jupyterlab_iframe --no-build 
jupyter serverextension enable --py jupyterlab_iframe 

# Github Jupyter Lab extension
jupyter labextension install @jupyterlab/github --no-build 

# Draw.io Jupyter Lab extension
jupyter labextension install jupyterlab-drawio --no-build 

# Rise Jupyter extension (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix

# Plotly Jupyter Lab extension
jupyter labextension install @jupyterlab/plotly-extension --no-build 

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc --no-build 

# Jupyter/Jupyterlab extension for proxying internal applications
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install jupyterlab-server-proxy

# JupyterLab extension mimerenderer to render HTML files in IFrame Tab. https://github.com/mflevine/jupyterlab_html
jupyter labextension install @mflevine/jupyterlab_html --no-build 

# Building everything up
jupyter lab build --dev

###############################################################
#          /jupyter/jupyterlab extensions/kernels              #
###############################################################